globo-technology/sic-ops

- src/main/java/sic/vista/swing/SeleccionDeProductosGUI.form
- src/main/java/sic/vista/swing/SeleccionDeProductosGUI.java
Se agrega un checkbox para que se llenen automáticamente por la cantidad total de productos, en la vista de seleccion de productos.
Cuando se edita la tabla, se quita la selección del mismo.
> Agrega la opción de seleccionar por la cantidad total todos los productos.

- src/main/java/sic/vista/swing/DetalleNotaDebitoGUI.java
- src/main/java/sic/vista/swing/PuntoDeVentaGUI.java
Cambia punto de venta para generar un pedido desde cualquier punto de acceso a la vista. Agrega iva a la nota de debito x.
> Modificaciones en ops.

- src/main/java/sic/modelo/Cliente.java
- src/main/java/sic/vista/swing/ClientesGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.form
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
Modifica la vista de clientes para mostrar la fecha del ultimo movimiento. Agrega el boton de pagos nuevamente a la vista de facturas de venta.
> Modifica las vistas de clientes y facturas de venta.

- src/main/java/sic/vista/swing/BuscarProductosGUI.java
- src/main/resources/Mensajes.properties
Agrega la regla de que un renglon de factura venta o pedido debe cumplir con la cantidad minima a la venta del producto.
> Valida cantidad mínima.

- src/main/java/sic/vista/swing/DetalleNotaDebitoGUI.java
Realiza correccion en la vista de detalle nota debito para que el campo de gasto administrativo funcione de manera correcta.
> Corrige la vista de detalle nota de debito.

- src/main/java/sic/vista/swing/BuscarProductosGUI.java
Agrega la request para verificar el stock a la hora de agregar un renglon.
> Corrige error en el control de stock.

- src/main/java/sic/vista/swing/FacturasCompraGUI.form
- src/main/java/sic/vista/swing/FacturasCompraGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.form
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
> Filtro por tipo de comprobante en compras

- src/main/java/sic/modelo/Caja.java
- src/main/java/sic/vista/swing/CajaGUI.java
- src/main/java/sic/vista/swing/CajasGUI.java
- src/main/java/sic/vista/swing/CuentaCorrienteGUI.java
Trae todos los movimientos de la caja al consultarla.
> HotfixCaja

- src/main/java/sic/vista/swing/DetalleClienteGUI.form
- src/main/java/sic/vista/swing/DetalleClienteGUI.java
- src/main/java/sic/vista/swing/DetalleUsuarioGUI.java
Realiza cambios en la vista de detalle cliente para indicar como obligatoria la credencial durante un alta.
Hace una selección automática del viajante o de la credencial si se realiza el alta de uno nuevo.
> Credencial obligatoria

- src/main/java/sic/vista/swing/NotasVentaGUI.java
- src/main/java/sic/vista/swing/RecibosCompraGUI.form
- src/main/java/sic/vista/swing/RecibosCompraGUI.java
- src/main/java/sic/vista/swing/RecibosVentaGUI.form
- src/main/java/sic/vista/swing/RecibosVentaGUI.java
@k31kur0n0 
Corresponde al ticket #136 de sic-ops
> Totalizador para recibos

- src/main/java/sic/vista/swing/PuntoDeVentaGUI.java
> Agrega get para mantener actualizado el cliente. 

- src/main/java/sic/modelo/ActualizarProductos.java
- src/main/java/sic/modelo/ProductosParaActualizar.java
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.java
> Cambia la vista de modificacion multiple para trabajar con el objeto de actualizacion multiple.

- src/main/java/sic/modelo/Ubicacion.java
- src/main/java/sic/vista/swing/DetalleClienteGUI.java
- src/main/java/sic/vista/swing/DetalleEmpresaGUI.java
- src/main/java/sic/vista/swing/DetalleLocalidadGUI.form
- src/main/java/sic/vista/swing/DetalleLocalidadGUI.java
- src/main/java/sic/vista/swing/DetalleProveedorGUI.java
- src/main/java/sic/vista/swing/DetalleTransportistaGUI.java
- src/main/java/sic/vista/swing/DetalleUbicacionGUI.form
- src/main/java/sic/vista/swing/DetalleUbicacionGUI.java
- src/main/java/sic/vista/swing/LocalidadesGUI.java
> Modifica el model de ubicacion y las vistas relacionadas.

- src/main/java/sic/vista/swing/CuentaCorrienteGUI.java
- src/main/java/sic/vista/swing/FacturasCompraGUI.form
- src/main/java/sic/vista/swing/FacturasCompraGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.form
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
- src/main/java/sic/vista/swing/NotasCompraGUI.form
- src/main/java/sic/vista/swing/NotasCompraGUI.java
- src/main/java/sic/vista/swing/NotasVentaGUI.form
- src/main/java/sic/vista/swing/NotasVentaGUI.java
- src/main/java/sic/vista/swing/RecibosCompraGUI.java
- src/main/java/sic/vista/swing/RecibosVentaGUI.java
> Quita los botones de eliminar de las vistas para administrar Facturas de venta y de compra

- src/main/java/sic/modelo/NuevoProducto.java
- src/main/java/sic/modelo/Producto.java
- src/main/java/sic/vista/swing/DetalleProductoGUI.form
- src/main/java/sic/vista/swing/DetalleProductoGUI.java
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.form
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.java
- src/main/java/sic/vista/swing/ProductosGUI.form
- src/main/java/sic/vista/swing/ProductosGUI.java
- src/main/resources/Mensajes.properties
> Agrega al model y a las vistas de producto, el atributo "destacado".

- src/main/java/sic/vista/swing/FacturasCompraGUI.form
- src/main/java/sic/vista/swing/FacturasCompraGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.form
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
- src/main/java/sic/vista/swing/PedidosGUI.form
- src/main/java/sic/vista/swing/PedidosGUI.java
> Agrega la busqueda de pedidos por producto.

- src/main/java/sic/modelo/ConfiguracionDelSistema.java
- src/main/java/sic/modelo/Factura.java
- src/main/java/sic/modelo/Recibo.java
- src/main/java/sic/vista/swing/CerrarVentaGUI.java
- src/main/java/sic/vista/swing/ConfiguracionDelSistemaGUI.java
- src/main/java/sic/vista/swing/DetalleFacturaCompraGUI.java
- src/main/java/sic/vista/swing/DetalleReciboGUI.java
- src/main/java/sic/vista/swing/PuntoDeVentaGUI.java
> Modifica los POST y PUT de los controllers de Recibo, Factura y Cds

- src/main/java/sic/vista/swing/GastosGUI.form
- src/main/java/sic/vista/swing/GastosGUI.java
- src/main/java/sic/vista/swing/PrincipalGUI.form
- src/main/java/sic/vista/swing/PrincipalGUI.java
- src/main/resources/Mensajes.properties
> Agrega la vista de administracion de gastos.

- src/main/java/sic/modelo/Factura.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
> Agrega en el listado de facturas de venta el nro de pedido.

- src/main/java/sic/vista/swing/CuentaCorrienteGUI.java
- src/main/java/sic/vista/swing/PedidosGUI.form
- src/main/java/sic/vista/swing/PedidosGUI.java
> Deshabilita los botones para crear nota credito y debito si el rol del usuario no es administrador o encargado.

- src/main/java/sic/modelo/Proveedor.java
- src/main/java/sic/vista/swing/BuscarProveedoresGUI.java
- src/main/java/sic/vista/swing/ClientesGUI.form
- src/main/java/sic/vista/swing/ClientesGUI.java
- src/main/java/sic/vista/swing/DetalleProveedorGUI.form
- src/main/java/sic/vista/swing/DetalleProveedorGUI.java
- src/main/java/sic/vista/swing/ProveedoresGUI.form
- src/main/java/sic/vista/swing/ProveedoresGUI.java
> Cambia codigo de proveedor por numero de proveedor.

- src/main/java/sic/vista/swing/ProductosGUI.form
- src/main/java/sic/vista/swing/ProductosGUI.java
> Elimina la busqueda por disponibilidad "todos" y agrega la busqueda de productos que se encuentren en stock.

- pom.xml
- src/main/java/sic/modelo/BusquedaFacturaCompraCriteria.java
- src/main/java/sic/modelo/BusquedaFacturaVentaCriteria.java
- src/main/java/sic/vista/swing/FacturasCompraGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
> Hace conocer a ops la criteria de busqueda de facturas de compra y de venta.

- src/main/java/sic/vista/swing/FormasDePagoGUI.form
- src/main/java/sic/vista/swing/FormasDePagoGUI.java
> Remueve la eliminación y modificacion de las formas de pago.

- src/main/java/sic/vista/swing/CerrarVentaGUI.java
- src/main/java/sic/vista/swing/DetalleCajaGUI.java
- src/main/java/sic/vista/swing/DetalleReciboGUI.java
- src/main/java/sic/vista/swing/FormasDePagoGUI.java
- src/main/java/sic/vista/swing/GastosGUI.java
- src/main/java/sic/vista/swing/PuntoDeVentaGUI.java
> Cambia las llamadas al service de forma de pago, para que no incluyan el id de empresa.

- src/main/java/sic/modelo/NuevaFacturaVenta.java
- src/main/java/sic/modelo/ProductosParaVerificarStock.java
- src/main/java/sic/vista/swing/BuscarProductosGUI.java
- src/main/java/sic/vista/swing/CerrarVentaGUI.java
- src/main/java/sic/vista/swing/NuevaFacturaVentaGUI.java
> Cambia el alta de Facturas de venta y la consulta por faltantes.

- src/main/java/sic/modelo/Cliente.java
- src/main/java/sic/modelo/NuevoProducto.java
- src/main/java/sic/modelo/Producto.java
- src/main/java/sic/modelo/ProductosParaActualizar.java
- src/main/java/sic/vista/swing/BuscarClientesGUI.java
- src/main/java/sic/vista/swing/ClientesGUI.java
- src/main/java/sic/vista/swing/DetalleClienteGUI.form
- src/main/java/sic/vista/swing/DetalleClienteGUI.java
- src/main/java/sic/vista/swing/DetallePedidoGUI.form
- src/main/java/sic/vista/swing/DetallePedidoGUI.java
- src/main/java/sic/vista/swing/DetalleProductoGUI.form
- src/main/java/sic/vista/swing/DetalleProductoGUI.java
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.form
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.java
- src/main/java/sic/vista/swing/NuevaFacturaVentaGUI.form
- src/main/java/sic/vista/swing/NuevaFacturaVentaGUI.java
- src/main/java/sic/vista/swing/ProductosGUI.java
> Bonificacion por Producto y limite por monto en Pedido

- src/main/java/sic/modelo/ProductosParaActualizar.java
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.form
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.java
> Poder modificar la cantidad minima en la modificacion multiple

- src/main/java/sic/modelo/Cliente.java
- src/main/java/sic/vista/swing/ClientesGUI.java
- src/main/java/sic/vista/swing/DetalleClienteGUI.form
- src/main/java/sic/vista/swing/DetalleClienteGUI.java
> Refactoring checkout MercadoPago

- src/main/java/sic/vista/swing/GastosGUI.form
- src/main/java/sic/vista/swing/GastosGUI.java
> Nuevo filtro por Forma de Pago en Gastos

- src/main/java/sic/modelo/NuevaFacturaCompra.java
- src/main/java/sic/modelo/NuevoRenglonFactura.java
- src/main/java/sic/modelo/NuevosResultadosComprobante.java
- src/main/java/sic/modelo/ProductoFaltante.java
- src/main/java/sic/modelo/ProductosParaActualizar.java
- src/main/java/sic/modelo/RenglonFactura.java
- src/main/java/sic/modelo/Resultados.java
- src/main/java/sic/vista/swing/BuscarProductosGUI.java
- src/main/java/sic/vista/swing/CerrarVentaGUI.java
- src/main/java/sic/vista/swing/DetalleFacturaCompraGUI.form
- src/main/java/sic/vista/swing/DetalleFacturaCompraGUI.java
- src/main/java/sic/vista/swing/DetallePedidoGUI.java
- src/main/java/sic/vista/swing/FacturasCompraGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
- src/main/java/sic/vista/swing/ModificacionMultipleProductosGUI.java
- src/main/java/sic/vista/swing/NuevaFacturaVentaGUI.java
- src/main/java/sic/vista/swing/ProductosFaltantesGUI.java
- src/main/resources/Mensajes.properties
> Refactoring de alta factura venta/compra

- src/main/java/sic/vista/swing/TraspasosGUI.form
- src/main/java/sic/vista/swing/TraspasosGUI.java
> Reporte de Traspaso

- src/main/java/sic/modelo/criteria/BusquedaTraspasoCriteria.java
- src/main/java/sic/vista/swing/TraspasosGUI.form
- src/main/java/sic/vista/swing/TraspasosGUI.java
> Agrega la busqueda por nro de pedido en traspasos.

- src/main/java/sic/vista/swing/NotasDebitoCompraGUI.java
> Elimina código no necesario.

- src/main/java/sic/modelo/LocalidadesParaActualizarDTO.java
- src/main/java/sic/vista/swing/LocalidadesGUI.form
- src/main/java/sic/vista/swing/LocalidadesGUI.java
- src/main/java/sic/vista/swing/ModificacionMultipleLocalidadesGUI.form
- src/main/java/sic/vista/swing/ModificacionMultipleLocalidadesGUI.java
> Modificacion multiples localidades

- src/main/java/sic/modelo/Rubro.java
- src/main/java/sic/vista/swing/DetalleRubroGUI.form
- src/main/java/sic/vista/swing/DetalleRubroGUI.java
> Poder navegar los productos filtrando por rubro

- src/main/java/sic/vista/swing/ProductosGUI.form
- src/main/java/sic/vista/swing/ProductosGUI.java
> Agrega al ordenamiendo de los resultados de la busqueda de producto, proveedor y rubro.

- src/main/java/sic/modelo/DetalleCompra.java
- src/main/java/sic/modelo/NuevaNotaCreditoDeFactura.java
- src/main/java/sic/modelo/NuevaNotaCreditoSinFactura.java
- src/main/java/sic/modelo/NuevaNotaDebitoSinRecibo.java
- src/main/java/sic/vista/swing/CuentaCorrienteGUI.java
- src/main/java/sic/vista/swing/DetalleNotaCreditoGUI.java
- src/main/java/sic/vista/swing/DetalleNotaDebitoGUI.java
- src/main/java/sic/vista/swing/FacturasCompraGUI.java
- src/main/java/sic/vista/swing/FacturasVentaGUI.java
- src/main/java/sic/vista/swing/NuevaNotaCreditoSinFacturaGUI.java
- src/main/java/sic/vista/swing/SeleccionDeProductosGUI.java
> Agregar la seccion de nota de credito y debito

- src/main/java/sic/modelo/criteria/BusquedaProductoCriteria.java
- src/main/java/sic/vista/swing/ProductosGUI.java
> Agrega al criterio de ordenamiento el segundo criterio de descripción para los casos en que se ordene por rubro y por proveedor
